######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 3 12:33:46 2009
######################################################################

VERSION = 3.0.1

TEMPLATE = subdirs
CONFIG += ordered release

SUBDIRS = src/klfbackend \
	  src/klf_cmdl \
	  src

