######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 3 12:33:46 2009
######################################################################

TEMPLATE = subdirs
CONFIG += ordered release

SUBDIRS = src/klfbackend \
	  src

